using System;
using System.Reflection;

namespace COMInteraction.InterfaceApplication.ReadValueConverters
{
    /// <summary>
    /// When values are returned from properties or methods from IInterfaceApplier generated by the InterfaceApplierFactory, the values are passed
    /// pasthrough an IReadValueConverter so that they can be manipulated if required
    /// </summary>
    public interface IReadValueConverter
    {
        /// <summary>
        /// The return value should be assignable to property.PropertyType otherwise the IInterfaceApplier.Apply method may fail
        /// </summary>
        object Convert(PropertyInfo property, object value);

        /// <summary>
        /// The return value should be assignable to method.ReturnType otherwise the IInterfaceApplier.Apply method may fail
        /// </summary>
        object Convert(MethodInfo method, object value);
    }
}
